Remove config groups model
ezr-ondrej/foreman pull request #7
Opened 2020-09-23 12:11 UTC by shiramax

2020-09-23 12:45 UTC, ezr-ondrej commented on app/models/host/managed.rb
> -  include_in_clone :config_groups, :host_config_groups, :host_classes, :host_parameters, :lookup_values
Note to myself: should be tested.

2020-09-23 12:47 UTC, ezr-ondrej commented on app/models/hostgroup.rb
> -  def self.search_by_config_group(key, operator, value)
Needs to get tested.

2020-09-23 12:54 UTC, ezr-ondrej approved these changes
I need to run the tests, but apart of it looks that matches what's been added.

2020-10-15 19:21 UTC, ezr-ondrej requested changes
We are missing drop of methods in https://github.com/theforeman/foreman_puppet_enc/pull/12/files#diff-d282d0fe7461e12531f5252b3aec5d5ba1efdcedad1ddf9fb4a1d8ea36dfca40R15-R39

2020-10-20 08:02 UTC, shiramax commented
@ezr-ondrej tests are failing due to this migration:
 https://github.com/ezr-ondrej/foreman/blob/develop/db/migrate/20140415032811_add_config_group_counter_defaults.rb 
Should I remove it from this PR?

2020-10-20 10:03 UTC, ezr-ondrej commented
> @ezr-ondrej tests are failing due to this migration:
> https://github.com/ezr-ondrej/foreman/blob/develop/db/migrate/20140415032811_add_config_group_counter_defaults.rb
> Should I remove it from this PR?

Yeah, eighter drop the migration completely, or just remove the model manipulation :)
Doesn't matter too much as we will drop it in the migration drop PR :)

2021-01-31 18:07 UTC, ezr-ondrej approved these changes
Thanks @shiramax :+1:

2021-01-31 18:07 UTC, merged